data_provider:
  root: /home/gridsan/agupta2/6.5940/celeba_split
  num_classes: 5
  base_batch_size: 1

run_config:
  # learning rate
  bs256_lr: 0.01
  # optimizer
  optimizer_name: sgd
  n_epochs: 20

net_config:
  net_name: mcunet-5fps