backward_config:
  enable_backward_config: 1
  freeze_fc: 0
  manual_weight_idx: 39-42-44-45-50-51-54-57
  n_bias_update: 21
  n_weight_update: null
  pw1_weight_only: 0
  quantize_gradient: 0
  train_scale: 0
  weight_select_criteria: magnitude+
  weight_update_ratio: 0.25-1-0-1-0-0.125-0.25-0.25
data_provider:
  base_batch_size: 1
  color_aug: 0.4
  dataset: image_folder
  image_size: 128
  n_worker: 8
  num_classes: 5
  resize_scale: 0.08
  root: /home/gridsan/agupta2/6.5940/mini_imagenet_split
evaluate: false
manual_seed: 0
net_config:
  cls_head: linear
  dropout: 0.0
  mcu_head_type: fp
  net_name: proxyless-w0.3
  pretrained: false
ray_tune: 0
resume: 0
run_config:
  base_lr: 0.025
  bias_only: 0
  bs256_lr: 0.1
  eval_per_epochs: 10
  fc_lr10: 0
  fc_only: 0
  grid_ckpt_path: null
  grid_output: null
  lr_schedule_name: cosine
  n_block_update: -1
  n_epochs: 20
  no_wd_keys:
  - norm
  - bias
  optimizer_name: sgd_scale_nomom
  warmup_epochs: 5
  warmup_lr: 0
  weight_decay: 0
run_dir: algorithm/runs/celeba/proxyless-w0.3/sparse_50kb/sgd_qas_nomom
