backward_config:
  enable_backward_config: 1
  freeze_fc: 0
  manual_weight_idx: 27-30-33-36-39-42-45-48
  n_bias_update: 25
  n_weight_update: null
  pw1_weight_only: 0
  quantize_gradient: 0
  train_scale: 0
  weight_select_criteria: magnitude+
  weight_update_ratio: 1-1-1-1-1-0.125-0.5-1
data_provider:
  base_batch_size: 64
  color_aug: 0.4
  dataset: image_folder
  image_size: 128
  n_worker: 8
  num_classes: 102
  resize_scale: 0.08
  root: /home/gridsan/agupta2/6.5940/flowers102_imagefolder
evaluate: false
manual_seed: 0
net_config:
  cls_head: linear
  dropout: 0.0
  mcu_head_type: fp
  net_name: mbv2-w0.35
  pretrained: false
ray_tune: 0
resume: 0
run_config:
  base_lr: 0.025
  bias_only: 0
  bs256_lr: 0.1
  eval_per_epochs: 10
  fc_lr10: 0
  fc_only: 0
  grid_ckpt_path: null
  grid_output: null
  lr_schedule_name: cosine
  mcu_head_type: quantized
  n_block_update: -1
  n_epochs: 50
  no_wd_keys:
  - norm
  - bias
  optimizer_name: sgd_scale_nomom
  warmup_epochs: 5
  warmup_lr: 0
  weight_decay: 0
run_dir: algorithm/runs/flowers/mbv2-w0.35/sparse_100kb/sgd_qas_nomom
